### ISSUE TITLE
specify version more clearly and make accessing old versions simple

### ISSUE THREAD

**Issue by HedvigS** [SietzeN/glottospace#55]
For reproducibility of research and transparency, it's good to be clear about versions of databases. I think it would be great if glottoget contained an argument for specifying also older versions of cldf-datasets and if the version used is clearly reported. One could even make it a required argument that the user has to specify version, but that might be pulling it to far. It's probably reasonable to make the users use the most recent version if they don't specify and make it possible to access older versions if they'd like.

**Comment by SietzeN** [comment]
I've made some changes to glottoget() 
CRAN policies determine that we cannot write to users directory. There can be exceptions if we ask the user explicitly.
Therefore, by default, glottospace now relies on built-in datasets. An added benefit is that many functions become much faster now because we don't need to check for the latest version and download it.

To accomodate your suggestion I've added three new arguments to glottoget().
- download: if TRUE, the newest version of a dataset will be downloaded. 
- dirpath: if a user wants to load or download a dataset from/to a specific local directory.
- url: A Zenodo url from which users can download an older version of a dataset.

**Comment by xrotwang** [comment]
If "built-in dataset" means a version of Glottolog distributed with glottospace, then it would be particularly important to let this version be known to the user - probably including citation information. (Cf. https://github.com/ropensci/lingtypology/issues/80#issuecomment-1041238675)

**Comment by HedvigS** [comment]
Yes, I agree with @xrotwang .  Thanks for seeing to that @SietzeN

**Comment by HedvigS** [comment]
Is there an easy way to use the conventional version numbering instead of Zenodo URLs? For example by having an inbuilt table which updates which URL matches which DOI and/or version?

**Comment by xrotwang** [comment]
FWIW, we are in the process of building a catalog of CLDF datasets which will probably include this information. May take a couple of weeks/months, though.

**Comment by HedvigS** [comment]
Sorry, maybe stupid question. When I go:

`glottospace::glottoget(glottodata = "glottobase")`

I don't know where to find the version number of Glottolog used.

I get the version information if I go download = T, but how do I know which version is stored internally in glottospace if I don't use the download option?
