### ISSUE TITLE
water in voronoi?

### ISSUE THREAD

**Issue by HedvigS** [SietzeN/glottospace#57]
What do you think of adding an optional argument to glottospace::glottospace() which specifies a radius of water to be included in the voronoi calculation? This would matter a fair deal for languages spoken on islands.

I know we're not dealing with polygons here but singular lat/long points for each languoid, so it's not like for example the entire Hawai'ian archipelago would be linked, but it would improve things somewhat still I think.

A default could be 200 nautical miles, which is the Exclusive Economic Zone limit decided on by UN (see example map of that below based on polygon landmasses). That's just a fairly neutral example, I could also imagine other defaults like[ 100 land miles which is what linguist Jeff Marck suggests is a reasonable overnight voyage in the Pacific.](https://sites.google.com/site/hedvigskirgard/pacific-maps#h.p_gglRFtMV0tD3)

![20-326a_Pacific_colour_EEZ-01](https://user-images.githubusercontent.com/5327845/152187164-3eb77090-b510-47e9-a62a-91cde0fe31f0.png)

**Comment by SietzeN** [comment]
Hi Hedvig,

Thanks for this suggestion. I like the idea. 

The difference off course is that the unit of analysis in glottospace are languages, and not the islands themselves (there can be multiple languages spoken on a single island). If we want to create Thiessen polygons for New Guinea for example, I think it makes sense to use the island boundaries to cut the polygons, rather than extending them into the ocean (although there will off course be some speakers that venture into the ocean;-). 

Regarding the buffers, there is already something like this built-in, but it still requires some work.
oc <- glottofilter(continent = "Oceania")
pac <- glottofiltermap(oc)
pacb <- glottospace(glottodata = pac, method = "buffer", radius = 100)
glottomap(pacb, projection = "pacific")

**Comment by HedvigS** [comment]
See... that's where I'd respectfully like to disagree :). What I imagine a user would want with the voronoi visualisation is among other things to see which language communities are neighbors. If that's the case, then water matters as much as tundra, desert, wheat fields or jungle. 

I might use the workaround then, but I think I'm not alone so it'd be neat if this was more built in.

**Comment by HedvigS** [comment]
I think it would help me here if I understood better what the purpose of the glottospace() function is. If it is to only show areas where speakers/signers live then as it is now it would include positively uninhabited and uninhabitable areas such as deserts, rivers, mountain peaks etc. If the idea is to give a sense of the area a language covers, be that by permanent settlement or other kinds of use then including water should be as obvious as including deserts etc.

I would kindly suggest that @SietzeN and Rik evaluate this once more if I may. You could set the default water buffer to a sensible value and let users set it to 0 if they do indeed want to disregard all water.

**Comment by SietzeN** [comment]
Hi @HedvigS 
I've now implemented this functionality and updated the description (see ?glottospace). Here's an example:

 glottodata <- glottofilter(country = "Philippines")
 glottopols <- glottospace(glottodata, radius = 100, method = "thiessen")
 glottomap(glottopols)

Could you check whether it works for you as expected? I will close this issue with the next push.

Cheers!
Sietze
